name: Vividarts docker image build
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Buid Docker image
                run: docker build -t calebyeboah:3.0
            
            -   name: Login to Docker
                run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            -   name: push image to Docker Hub
                run: docker push calebyeboah/vividarts:3.0 
